name: ci-ad

on:
  push:
    paths:
      - 'src/ad/**'
      - 'pb/demo.proto'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Copy proto file
        run: |
          mkdir -p src/ad/proto
          cp pb/demo.proto src/ad/proto/demo.proto

      - name: Grant execute permission for gradlew
        run: chmod +x src/ad/gradlew

      - name: Build with Gradle
        run: |
          cd src/ad
          ./gradlew installDist -PprotoSourceDir=./proto

      # Optional: Add Gradle test step if unit tests exist
      # - name: Run tests
      #   run: |
      #     cd src/ad
      #     ./gradlew test

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: src/ad
          file: src/ad/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ad:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/ad:${{ github.run_id }}|" kubernetes/ad/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/ad/deploy.yaml
          git commit -m "[CI] update ad image tag"
          git push origin HEAD:main -f
