name: ci-accounting

on:
  push:
    paths:
      - 'src/accounting/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: |
          cd src/accounting
          go mod download
          go build -o accounting-service main.go

      - name: Run tests
        run: |
          cd src/accounting
          go test ./...

      - name: Docker build & push
        uses: docker/build-push-action@v6
        with:
          context: src/accounting
          file: src/accounting/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/accounting:${{ github.run_id }}

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/accounting:${{ github.run_id }}|" kubernetes/accounting/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/accounting/deploy.yaml
          git commit -m "[CI] update accounting image tag"
          git push origin HEAD:main -f

