name: ci-accounting

on:
  push:
    paths:
      - 'src/accounting/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          cd src/accounting
          dotnet restore

      - name: Copy proto file
        run: |
          mkdir -p src/accounting/proto
          cp pb/demo.proto src/accounting/proto/demo.proto

      - name: Build
        run: |
          cd src/accounting
          dotnet build --no-restore --configuration Release

      - name: Test
        run: |
          cd src/accounting
          dotnet test --no-build --verbosity normal

      - name: Docker build & push
        uses: docker/build-push-action@v6
        with:
          context: src/accounting
          file: src/accounting/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/accounting:${{ github.run_id }}

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/accounting:${{ github.run_id }}|" kubernetes/accounting/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/accounting/deploy.yaml
          git commit -m "[CI] update accounting image tag"
          git push origin HEAD:main -f
