name: ci-cart

on:
  push:
    paths:
      - 'src/cart/**'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust if targeting a different .NET version

      - name: Debug - List repository structure
        run: |
          pwd
          ls -R src/cart

      - name: Restore dependencies
        run: |
          cd src/cart/src
          dotnet restore cart.csproj

      - name: Build
        run: |
          cd src/cart/src
          dotnet build cart.csproj --no-restore --configuration Release

      # Optional: Add unit tests if available
      # - name: Run tests
      #   run: |
      #     cd src/cart/src
      #     dotnet test cart.csproj --no-build --configuration Release

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps
