name: ci-cart

on:
  push:
    paths:
      - 'src/cart/**'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust if targeting a different .NET version

      - name: Debug - List repository structure
        run: |
          pwd
          ls -R src/cart

      - name: Restore dependencies
        run: |
          cd src/cart/src
          dotnet restore cart.csproj

      - name: Build
        run: |
          cd src/cart/src
          dotnet build cart.csproj --no-restore --configuration Release

      # Optional: Add unit tests if available
      # - name: Run tests
      #   run: |
      #     cd src/cart/src
      #     dotnet test cart.csproj --no-build --configuration Release

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: src/cart/src
          file: src/cart/src/Dockerfile  # Adjust if your Dockerfile is here, else point to its actual path
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cart:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/cart:${{ github.run_id }}|" kubernetes/cart/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/cart/deploy.yaml
          git commit -m "[CI] update cart image tag"
          git push origin HEAD:main -f
