name: ci-currency

on:
  push:
    paths:
      - 'src/currency/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake autoconf libtool pkg-config git

      - name: Install Protobuf v21.12
        run: |
          git clone --depth=1 --branch v21.12 https://github.com/protocolbuffers/protobuf.git
          cd protobuf/cmake
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -Dprotobuf_BUILD_TESTS=OFF
          make -j$(nproc)
          sudo make install
          cd ../../../
          rm -rf protobuf

      - name: Install gRPC
        run: |
          git clone --recurse-submodules -b v1.59.0 https://github.com/grpc/grpc
          cd grpc
          mkdir -p cmake/build
          cd cmake/build
          cmake ../.. -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install
          cd ../../../
          rm -rf grpc

      - name: Build Currency Service
        run: |
          cd src/currency
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
          ls -la

      # Optional: Add docker build & push if you deploy it as container
      # - name: Docker build & push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./src/currency
      #     file: ./src/currency/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/currency:${{ github.run_id }}
