name: ci-currency

on:
  push:
    paths:
      - 'src/currency/**'
      - 'pb/demo.proto'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build essentials and dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake git autoconf libtool pkg-config unzip

      - name: Install gRPC and Protobuf
        run: |
          # Install Protobuf
          git clone --recurse-submodules -b v24.0 https://github.com/protocolbuffers/protobuf
          cd protobuf
          mkdir build && cd build
          cmake .. && make -j$(nproc)
          sudo make install
          sudo ldconfig
          cd ../..

          # Install gRPC
          git clone --recurse-submodules -b v1.62.0 https://github.com/grpc/grpc
          cd grpc
          mkdir -p cmake/build && cd cmake/build
          cmake ../.. -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF
          make -j$(nproc)
          sudo make install
          cd ../../../

      - name: Install Google Benchmark
        run: |
          git clone https://github.com/google/benchmark.git
          cd benchmark
          git clone https://github.com/google/googletest.git
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install
          cd ../..

      - name: Install OpenTelemetry C++
        run: |
          git clone https://github.com/open-telemetry/opentelemetry-cpp.git
          cd opentelemetry-cpp
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
          make -j$(nproc)
          sudo make install
          cd ../..

      - name: Copy proto file
        run: |
          mkdir -p src/currency/proto
          cp pb/demo.proto src/currency/proto/demo.proto

      - name: Build Currency Service
        run: |
          cd src/currency
          mkdir -p build
          cd build
          export CMAKE_PREFIX_PATH="/usr/local;/usr/local/lib/cmake"
          cmake ..
          make -j$(nproc)

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/currency/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/currency:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/currency:${{ github.run_id }}|" kubernetes/currency/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/currency/deploy.yaml
          git commit -m "[CI] update currency image tag"
          git push origin HEAD:main -f
