name: ci-currency

on:
  push:
    paths:
      - 'src/currency/**'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ autoconf libtool pkg-config git

      - name: Install gRPC and Protobuf
        run: |
          # Install Protobuf
          git clone --depth=1 --branch v21.12.0 https://github.com/protocolbuffers/protobuf.git
          cd protobuf/cmake
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install
          cd ../../..

          # Install gRPC
          git clone --depth=1 --branch v1.62.0 https://github.com/grpc/grpc
          cd grpc
          git submodule update --init
          mkdir -p cmake/build
          cd cmake/build
          cmake ../.. -DCMAKE_BUILD_TYPE=Release -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF
          make -j$(nproc)
          sudo make install
          cd ../../..

      - name: Build Currency Service
        run: |
          cd src/currency
          mkdir -p build
          cd build
          cmake ..
          make

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .                        # build context is repo root
          file: src/currency/Dockerfile     # adjust if your Dockerfile is here
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/currency:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/currency:${{ github.run_id }}|" kubernetes/currency/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/currency/deploy.yaml
          git commit -m "[CI] update currency image tag"
          git push origin HEAD:main -f
