name: ci-checkout

on:
  push:
    paths:
      - 'src/checkout/**'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Debug - List repository structure
        run: |
          pwd
          ls -R src/checkout

      - name: Build
        run: |
          cd src/checkout
          go mod tidy
          go build -o checkout main.go

      - name: Unit Tests
        run: |
          cd src/checkout
          go test ./...

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .                        # build context is repo root
          file: src/checkout/Dockerfile     # Dockerfile location
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/checkout:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/checkout:${{ github.run_id }}|" kubernetes/checkout/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/checkout/deploy.yaml
          git commit -m "[CI] update checkout image tag"
          git push origin HEAD:main -f
