name: ci-currency

on:
  push:
    paths:
      - 'src/currency/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (build-essential, cmake, protobuf, grpc)
        run: |
          sudo apt update
          sudo apt install -y build-essential autoconf libtool pkg-config cmake git

          # Install Protobuf v3.21.12 without building tests
          git clone --depth=1 --branch v21.12.0 https://github.com/protocolbuffers/protobuf.git
          cd protobuf/cmake
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -Dprotobuf_BUILD_TESTS=OFF
          make -j$(nproc)
          sudo make install
          cd ../../..

          # Install gRPC v1.62.0
          git clone --depth=1 --branch v1.62.0 https://github.com/grpc/grpc
          cd grpc
          git submodule update --init
          mkdir -p cmake/build
          cd cmake/build
          cmake ../.. -DCMAKE_BUILD_TYPE=Release -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF
          make -j$(nproc)
          sudo make install
          cd ../../..

      - name: Debug - list src/currency contents
        run: |
          ls -R src/currency

      - name: Build Currency Service
        run: |
          cd src/currency
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: src/currency
          file: src/currency/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/currency:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Kubernetes manifest with new image
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/currency:${{ github.run_id }}|" kubernetes/currency/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/currency/deploy.yaml
          git commit -m "[CI] Update currency image tag to ${{ github.run_id }}"
          git push origin HEAD:main -f
