name: ci-currency

on:
  push:
    paths:
      - 'src/currency/**'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    container:
      image: rajeshkumardevops/cpp-builder:latest  # ✅ your prebuilt builder image on Docker Hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - Show files
        run: |
          pwd
          ls -R src/currency

      - name: Build Currency Service
        run: |
          cd src/currency
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Currency Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./src/currency
          file: ./src/currency/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/currency:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/currency:${{ github.run_id }}|" kubernetes/currency/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/currency/deploy.yaml
          git commit -m "[CI] update currency image tag"
          git push origin HEAD:main -f

      # Optional: kubectl apply if your runner has kubeconfig
      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f kubernetes/currency/deploy.yaml
