name: ci-frontend

on:
  push:
    paths:
      - 'src/frontend/**'
      - 'pb/demo.proto'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Copy proto file
        run: |
          mkdir -p src/frontend/protos
          cp pb/demo.proto src/frontend/protos/demo.proto

      - name: Install dependencies
        run: |
          cd src/frontend
          npm ci

      - name: Generate proto files
        run: |
          cd src/frontend
          npx grpc_tools_node_protoc \
            --js_out=import_style=commonjs,binary:./protos \
            --grpc_out=grpc_js:./protos \
            --ts_out=grpc_js:./protos \
            -I ../../pb ../../pb/demo.proto

      - name: Build
        run: |
          cd src/frontend
          npm run build

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_id }}|" kubernetes/frontendproxy/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/frontendproxy/deploy.yaml
          git commit -m "[CI] update frontend image tag"
          git push origin HEAD:main -f
