name: ci-frontend-proxy

on:
  push:
    paths:
      - 'src/frontend-proxy/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd src/frontend-proxy
          npm install

      - name: Build
        run: |
          cd src/frontend-proxy
          npm run build || echo "No build script defined, skipping build."

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/frontend-proxy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend-proxy:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/frontend-proxy:${{ github.run_id }}|" ultimate-devops-project-demo/kubernetes/frontendproxy/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add ultimate-devops-project-demo/kubernetes/frontendproxy/deploy.yaml
          git commit -m "[CI] update frontend-proxy image tag"
          git push origin HEAD:main -f
