name: ci-frontend-proxy

on:
  push:
    paths:
      - 'src/frontend-proxy/**'
      - 'src/frontend-proxy/envoy.tmpl.yaml'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build validation
        run: |
          echo "No build step defined for frontend-proxy. Add build steps here if required."
          
      - name: Test placeholder
        run: |
          echo "No test suite defined for frontend-proxy. Add tests here if available."

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/frontend-proxy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend-proxy:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/frontend-proxy:${{ github.run_id }}|" kubernetes/frontend-proxy/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/frontend-proxy/deploy.yaml
          git commit -m "[CI] update frontend-proxy image tag"
          git push origin HEAD:main -f
