name: ci-flagd-ui

on:
  push:
    paths:
      - 'src/flagd-ui/**'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: src/flagd-ui
        run: npm ci

      - name: Build
        working-directory: src/flagd-ui
        run: npm run build

      - name: Test
        working-directory: src/flagd-ui
        run: npm test

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/flagd-ui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flagd-ui:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/flagd-ui:${{ github.run_id }}|" kubernetes/flagd-ui/deploy.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.email "rkr11391@gmail.com"
          git config --global user.name "rajeshdevopsprac"
          git add kubernetes/flagd-ui/deploy.yaml
          git commit -m "[CI] update flagd-ui image tag"
          git push origin HEAD:main -f
